[build]
base="/"
publish="pub/"
functions="functions/"
command="make build"

[build.environment]
GO_IMPORT_PATH="github.com/mna/netlify-test"

[[redirects]]
from="/"
to="/hello.html"

[[redirects]]
from="/*"
to="/.netlify/functions/server?path=:splat"
status=200
force=false
